---
- name: This is used to deploy the latest version of Yazz publicly
  hosts: webservers
  vars:
    PROCESS: node
  tasks:


    - name: Kill running processes
      shell: "killall node"
      ignore_errors: yes


    - command: git reset --hard origin/master
      args:
        chdir: /root/visifile


    - name: install the latest version of Yazz
      git:
        repo: 'https://github.com/yazz/yazz.git'
        dest: /root/visifile


    - name: build docs
      shell:
          cmd: asciidoc   -d book   main.adoc
      args:
          chdir: /root/visifile/public/visifile/docs/book/



    - name: Start Yazz
      shell:
          cmd:  (while true; do    node src/electron.js --port 443 --public {{ ssl_public_key }} --private {{ ssl_private_key }} --host {{ use_host }}  --usehost {{ use_host }} --https true --hostport 443 --centralhost {{ use_host }} --centralhostport 443 --centralhosthttps true --cacert1 {{ ssl_cacert1 }} --cacert2 {{ ssl_cacert2 }} --cacert3 {{ ssl_cacert3 }} --showdebug true  --virtualprocessors 20   --hideimportbuttons true > nohup.out; done) 
      async: 10
      poll: 0
      args:
        chdir: /root/visifile/
